server:
  port: 8086
  servlet:
    context-path: /wallet-service
spring:
  application:
    name: Wallet-Service
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      # host: cluster0.fzri6qs         # MongoDB server hostname or IP address
      port: 27017               # MongoDB server port
      database: testing           # Database name
      authentication-database: admin   # Authentication database (optional)
      uri: mongodb+srv://root:root@cluster0.fzri6qs.mongodb.net/testing
springdoc:
  swagger-ui:
    path: /swagger-ui.html